In [1]:
%cd ..

f:\nn

# Importing Libraries

In [2]:
import pandas as pd
import numpy as np 
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from glob import glob
from tqdm import tqdm
from utils.resize_script import resize_images

# Importing Images

In [3]:
df = pd.read_csv('data/images_path.csv')
df.head()

                                    path    class
0  data\Bangunan Retak\Cracked\00001.jpg  Cracked
1  data\Bangunan Retak\Cracked\00002.jpg  Cracked
2  data\Bangunan Retak\Cracked\00003.jpg  Cracked
3  data\Bangunan Retak\Cracked\00004.jpg  Cracked
4  data\Bangunan Retak\Cracked\00005.jpg  Cracked

In [4]:
image_size = set()
for path in df['path']:
    img = Image.open(path)
    image_size.add(img.size)
print("Unique image sizes: ", image_size)

Unique image sizes:  {(256, 256), (227, 227)}

# Resizing our Images

In [5]:
df =  resize_images(df, resize_size=227, output_path = "data/cracked_vs_non_cracked_resized")
display(df.head())

Resizing images...

100%|██████████| 96092/96092 [02:39<00:00, 602.32it/s]

,path,class,resized_path
0,data\Bangunan Retak\Cracked\00001.jpg,Cracked,data\cracked_vs_non_cracked_resized\Cracked\00...
1,data\Bangunan Retak\Cracked\00002.jpg,Cracked,data\cracked_vs_non_cracked_resized\Cracked\00...
2,data\Bangunan Retak\Cracked\00003.jpg,Cracked,data\cracked_vs_non_cracked_resized\Cracked\00...
3,data\Bangunan Retak\Cracked\00004.jpg,Cracked,data\cracked_vs_non_cracked_resized\Cracked\00...
4,data\Bangunan Retak\Cracked\00005.jpg,Cracked,data\cracked_vs_non_cracked_resized\Cracked\00...

# Ensuring that all of the new images have the same dimensions

In [6]:
image_size = set()
for path in df['resized_path']:
    img = Image.open(path)
    image_size.add(img.size)
print("Unique image sizes: ", image_size)

Unique image sizes:  {(227, 227)}

# Saving our Resized Images path in a CSV file

In [7]:
df.to_csv(r'data/df_resized.csv', index=False)